### ISSUE TITLE
Object planes are broken

### ISSUE THREAD

**Issue by ngrewe** [gnustep/libobjc2#11]
Hi David,

I was recently bored out of my wits and wanted to test drive some wonky ideas involving object planes. Turns out that the object plane support, as advertised in the README, is a few sorts of broken right now. Here's the list of issues I have:
- The `objc_plane_lookup()` hook is not exposed for external consumers.
- There is a [commented out test](https://github.com/gnustep/libobjc2/blob/master/sendmsg2.c#L163-L169) for the sender being nil and the nonexistent `_CLS_PLANE_AWARE` flag that has a comment about the object pointers potentially being invalid. For testing I only kept the `sender == nil` test, which didn't make brimstone rain down on me, but maybe you can shed some light on the corner cases involved here. It's a bit opaque to me, but I'm speculating that it's related to GC?
- There seems to be a fundamental incompatibility between object planes and small objects, since you don't have the additional space to store the plane identifier in the word before the small object. I'd be prepared to accept that and say that small objects are always part of the global plane.
- `objc_msgSend()` is not sender-aware, and hence can't make any decisions on whether it should take the fast path (when both objects are in the same plane), or go through the slowMsgLookup mechanism, which would then delegate to the plane lookup hook.

Obviously, since it's not working at all presently, it might make some sense to remove the object plane support, but I think you should be able to build some seriously cool stuff with it. I'd be willing to work on that, but I think I need some input. The `objc_msgSend()` issue seems particularly tricky, since it seems to involve changing the runtime ABI.

Cheers,

Niels

**Comment by davidchisnall** [comment]
Yup, this is all true.  I eventually came to the conclusion that it was effectively impossible to retrofit object plane support to Objective-C in the way that I'd originally considered.  In particular, the mapping from sender to plane was a sufficiently noticeable performance hit that I didn't want to enable it by default.  I'd be more tempted to have a per-thread plane context at a fixed offset in the TLS region so that we could access it very cheaply.  

To really implement object planes well, you also need a privilege transition.  Part of the reason that I stopped working on it was that it really needed some hardware support.  We [now have that support](http://chericpu.org), though most other people don't.  Implementing good support for object planes is definitely something that would be interesting in this context.

**Comment by ngrewe** [comment]
>  In particular, the mapping from sender to plane was a sufficiently noticeable performance hit that I didn't want to enable it by default.

I'm just reconstructing how it's supposed to work from a cursory study of the existing code, so I might not have the whole picture: Could you explain a bit where the performance hit comes from? Currently the plane is an opaque identifier in the word before the object pointer. So I expected the overhead being just loading that into memory for the sender and comparing the plane IDs. Is that sufficient to degrade performance because you'd mess up the cache? 

>  I'd be more tempted to have a per-thread plane context at a fixed offset in the TLS region so that we could access it very cheaply.

What I actually had in mind was trying to see how far you could get with building an actor system on top of libobjc2 and libdispatch (while just writing the minimal amount of proxies, futures etc. in Objective-C). The idea was to use object planes to isolate the actors, and put messages sent across plane boundaries onto dispatch queues functioning as mailboxes. Having per-thread planes wouldn't actually help for that.

> it really needed some hardware support. We now have that support

That looks fairly exciting!

**Comment by davidchisnall** [comment]
> Could you explain a bit where the performance hit comes from? 

The message send path is performance critical.  Anything added to that path slows things down and an extra load + mask + conditional added around 20-30% to message send cost.
> What I actually had in mind was trying to see how far you could get with building an actor system on top of libobjc2 and libdispatch

I've recently had issues with doing something like this and gone back to passing blocks between threads.  The issue is with the calling convention.  Anything that returns a `struct` must leave the caller's stack frame alone until the callee returns (because the hidden argument is a pointer to the caller's stack space).  Additionally, any method with c++ objects as arguments will need copy / move constructors called (my case involved passing `std::shared_ptr` values between threads, and this broke horribly).  

> Having per-thread planes wouldn't actually help for that.

It will if the receiver's plane does not match the sender thread's plane ID.
