### ISSUE TITLE
objc_direct methods

### ISSUE THREAD

**Issue by digital-pers0n** [gnustep/libobjc2#165]
[GNU runtime doesn't support direct calls at this time](https://github.com/llvm/llvm-project/blob/a61fa1a4b9d247e34ea5541422f7040a37baf6e7/clang/lib/CodeGen/CGObjCGNU.cpp#L3901)
Aren't they just simple C-functions?

**Comment by davidchisnall** [comment]
Not quite.  They also need to ensure that the +initialize method is invoked.  There's a comment in the Mac version that describes some of this:

```
  // Generate:
  //
  // /* for class methods only to force class lazy initialization */
  // self = [self self];
  //
  // /* unless the receiver is never NULL */
  // if (self == nil) {
  //     return (ReturnType){ };
  // }
  //
  // _cmd = @selector(...)
```

I think this is actually wrong, because if you do `objc_allocateInstance` and then send it a message, it won't call `+initialize` and they've broken the language semantics.

**Comment by davidchisnall** [comment]
I don't really like requiring a message send here, because it largely defeats the point of direct messages for efficiency.  I'm tempted to add an `__objc_initialize` function to guarantee that `+initialize` has been called.  I'm also tempted to make the caller responsible for calling it - if a static method is called from within another method on the same class (or a subclass) it can be elided, and a little bit of analysis should allow it to be elided elsewhere as well.

**Comment by digital-pers0n** [comment]
Looks like they know about this problem.
[several entry points for direct methods](https://github.com/llvm/llvm-project/blob/ec2e3e331e6d60dee77e4da83bbb192597069f15/clang/lib/CodeGen/CGObjC.cpp#L784)
[unnecessary class initialization in direct methods](https://github.com/llvm/llvm-project/blob/ec2e3e331e6d60dee77e4da83bbb192597069f15/clang/lib/CodeGen/CGObjCMac.cpp#L4120)
Also in the recent Apple's objc runtime there are new runtime functions to bypass objc_msgSend for rarely overridden methods
such as self, new, class, isKindOfClass and respondsToSelector the functions are prefixed with objc_opt_* [NSObject.mm](https://opensource.apple.com/source/objc4/objc4-818.2/runtime/NSObject.mm.auto.html)

**Comment by davidchisnall** [comment]
It looks as if the code for the `objc_opt_` stuff is not in the public LLVM, only in Apple's fork.
