### ISSUE TITLE
How can I install gnustep in alpine linux

### ISSUE THREAD

**Issue by ShawnBaek** [gnustep/libobjc2#168]

**Comment by plaurent** [comment]
Good question, I am investigating this for the PinePhone running PostmarketOS alpine and will post my findings as a script at https://github.com/plaurent/gnustep-build

**Comment by ShawnBaek** [comment]
Thanks I want to install using apk add package on iSH app. I can’t wait to get gnustep on Alpine Linux. Thanks

**Comment by davidchisnall** [comment]
This is quite off-topic to ask in the runtime issue tracker.  You should be able to build the runtime in the same way on Alpine as you do on any other architecture (`mkdir libobjc2-build ; cd libobjc2-build ; cmake -G Ninja /path/to/libobjc2/src ; ninja`).  If this does not work on Alpine, please file specific issues.

**Comment by davidchisnall** [comment]
I misread the link and thought this was filed on a different repository.  Sorry for the noise.

As I understand it, the main difference between Alpine and other mainstream distros is that it uses musl instead of glibc as the system libc.  I would not expect this to cause any compatibility problems: the main difference is the lack of complete locale support in musl, but GNUstep typically uses ICU for that and only falls back to the libc code (sometimes) if ICU is not available.  Please file issues on the relevant repositories if something doesn't build / work with musl.

**Comment by davidchisnall** [comment]
No, I was right the first time and was just confused by the gnustep-build link.  Building GNUstep as a whole is off-topic for the runtime's issue tracker.
