### ISSUE TITLE
libobjc2 should be buildable from the MSYS2 command line...

### ISSUE THREAD

**Issue by gcasa** [gnustep/libobjc2#192]
It is necessary for this library to be buildable and usable just like any other library in MSYS2 so that we can utilize ObjC2 features when building from the MSYS2 command line.

**Comment by triplef** [comment]
How does this differ from #190?

**Comment by davidchisnall** [comment]
There is currently no MinGW Objective-C ABI and the hacks that MinGW does to combine the Itanium and Windows C++ ABIs make it very hard to add one.

**Comment by gcasa** [comment]
Hard or not that still does not change the fact that this library is not as portable as it should be.  

This shortcoming has caused quite a bit of grief at my current position and things would have been greatly simplified if this had been considered.

Given that you said to me in the past that if I wanted to do these changes I could and you would consider merging them I am going to take you up on that offer.    

I will create a branch or a fork and when it is ready for review I will let you know.  GC

**Comment by davidchisnall** [comment]
Happy to take a PR, but it will require working with the MinGW team to ensure that they are exposing the right symbols to allow interop with their C++ EH model.  This is complicated because they are layering Itanium-style EH on top of SEH in a complicated way.  You'll also need to modify clang to handle the mingw target triple.

I'd suggest that, if you *really* want to suffer through all of this, that you start with a design doc proposing all of the things that you need to change and how you plan on changing them.
