### ISSUE TITLE
libobjc2 has no support for extended protocol types

### ISSUE THREAD

**Issue by theiostream** [gnustep/libobjc2#37]
From what I could understand, Clang is able to emit an `extendedMethodProperties` to an objc runtime protocol struct (https://github.com/llvm-mirror/clang/blob/a38ba9770a70056f9fdd6c71f819e5db45a105e4/lib/CodeGen/CGObjCMac.cpp#L2989). This property in turn is used to store a type encoding for a protocol method capable of telling us more about the method.

For instance, instead of purely `@` for an object, we get its class too.

Apple's libobjc2 provides the private function

```
extern const char *_protocol_getMethodTypeEncoding(Protocol *p, SEL sel, BOOL isRequiredMethod, BOOL isInstanceMethod);
```

which gets this "special" type encoding. (an example can be found in https://gist.github.com/0xced/4969438)

How could I go about implementing support for this?

**Comment by davidchisnall** [comment]
This will be an ABI change, because clang doesn't currently emit it for the GNUstep runtime.  You'll need to modify `lib/CodeGen/CGObjCGNU.cpp` in clang to emit the encoding in a new field in the method structure (ideally, rather than extending the protocol as Apple has done), extend the struct in `method_list.h` in libobjc2, and bump the ABI version in the class that clang uses when targeting `-fobjc-runtime=gnustep-1.9` or newer and then have the runtime upgrade the method structures from old classes to point to the new one.

**Comment by davidchisnall** [comment]
The new ABI now has this information.
