### ISSUE TITLE
Constant string layout with ABI 2.0

### ISSUE THREAD

**Issue by minusbat** [gnustep/libobjc2#86]
So, I assume that the compiler always lays out a constant string directly as two instance variables - a pointer to a null terminated C string and a length. Its been this way as long as I can remember, still seems to be this way using the 1.9 ABI as well. When I switch to the 2.0 ABI something goes wrong though, which I haven't got to the bottom of - I get the length fine, but I get a corrupt pointer for the string itself. Very small piece of code below shows this. It's based on your 'a.m' from the other issue actually ;-) It has an Obt root class, a Str class with the pointer and length, and an NSConstantString subclass of Str. One method 'puts' which outputs the string, and then I call it with a constant "hello world".

This works under ABI 1.9, but coredumps on 2.0. I suspect I have misunderstood something that has changed here (and possibly I have been doing it wrong for two decades and have only got away with it by luck until now maybe?). So this may well not be a bug, not sure.

I compile this with
 "clang70 -I . -fobjc-runtime=gnustep-2.0  a.m libobjc.a" in the build directory

```
#include <objc/runtime.h>
#include <stdio.h>

@interface Obj
@end
@implementation Obj {
        Class isa;
} @end

@interface Str : Obj
- (void)puts;
@end

@implementation Str {
        char *ptr;
        int len;
}
- (void)puts {
        puts(ptr);
} @end

@interface NSConstantString : Str
@end

@implementation NSConstantString
@end

int main()
{
        [@"hello world" puts];
}
```

**Comment by davidchisnall** [comment]
Yup, one of the breaking changes in the 2.0 ABI is to change the string representation.  See [this comment](https://github.com/gnustep/libobjc2/issues/82#issuecomment-462256851) in Issue #82 for the change.  Constant strings are now either tiny strings that are embedded in the pointer or they are a richer structure with space for a hash (very important for performance if you're using them in a dictionary).  They can be either ASCII or UTF-16, for better alignment with the OpenStep / Cocoa APIs (which deal with UTF-16 code units, so `-characterAtIndex:` can now always be a constant-time operation with the new layout).  

Note that on macOS, the constant string layout is also different and matches the `CFConstantString` C type.

**Comment by davidchisnall** [comment]
I forgot to say, the compiler will set `__OBJC_GNUSTEP_RUNTIME_ABI__ >= 20` if it's using the new strings ABI, so you can test at compile time which layout you should be using.  GNUstep does this already, but I guess you're using a different `NSConstantString` implementation?

**Comment by minusbat** [comment]
Yes, I have my own set of foundation objects, which is why I always get tripped up by this stuff :-) OK, that makes sense. Will have to go and investigate how to support this though - basically I have everything in a subclass which assumes it can get hold of a C pointer to the string in UTF-8 to work with. I assume what you do is provide separate implementations for the different formats ?

Given an objects how can I identify if its a tiny string or a normal one, and if so then whether its in UTF-16 or not (indeed, what makes the compiler output UTF-16 strings? I have a lot of literal UTF-8 strings in my code with things like japanese text i  them, will this break?)

**Comment by minusbat** [comment]
BTW, you say "one of the breaking changes" - which kind of implies there are others :-) Is there a list anywhere ?

**Comment by davidchisnall** [comment]
That's probably the only one that matters to Foundation authors, the rest are mostly compiler-runtime contracts.

If it's a tiny string, the low bit of the pointer will be 4.  You can use the [`objc_registerSmallObjectClass_np` function](https://github.com/gnustep/libobjc2/blob/2edfe64739f6348c2545d2eeb365a6994b972eef/objc/runtime.h#L987) to set a class for these, for the purpose of message passing.  Note that this object does not have an `isa` pointer and all of its data is contained within the `self` pointer (which is not actually a pointer).  The compiler will generate these for any string that is 8 or fewer characters and is (7-bit) ASCII.

Anything that is longer than 8 characters will be represented as a proper object, with [this layout)(https://github.com/gnustep/libobjc2/blob/2edfe64739f6348c2545d2eeb365a6994b972eef/loader.c#L113).  The ABI defines ASCII, UTF-8, UTF-16, and UTF-32 representations, but currently the compiler uses only the ASCII and UTF-16 versions.

If you have a string literal in UTF-8 source, clang will transform it to UTF-16 when it generates the constant string object.  Your `NSConstantString` implementation will need to handle the case that it's UTF-16 internally.  Hopefully that's not too much effort, because the public `NSString` APIs are all in terms of UTF-16 code units.  If you've got a lot of Japanese text, hopefully this will end up being better for you because now your average number of bytes per character goes from 3 (UTF-8) to 2 (UTF-16) and you no longer have to deal with a variable length mapping from indexes into a UTF-8 string to indexes into a UTF-16 string.

By the way, is your Foundation implementation open source?

**Comment by minusbat** [comment]
Ah, brilliant, thanks for the explanation. One question  when you say '8 or fewer' for the tiny string, does that include the terminating zero ? i.e. can I just use the address of the pointer as if it was the address of the C-string. That would help a lot!

As for the UTF-16, that is probably going to be a killer for me unfortunately. I don't implement the NeXT style APi's really, I have my own, and I based them around all strings being UTF-8 and being easily able to access the C-string. So all my methods work with strings by using the base of the UTF-8 string and the C library. Its good enough for what I need it for. To handle mixed encodings would involve implementing lots of different combinations of methods, or having methods which convert anything in UTF-16 back to UTF-8, which would be slow. What are the chances of me getting a flag to clang to tell it to make all strings UTF-8 instead of Utf-16 I wonder ? :-) [actually, may look at doing that!]

I handled the variable index thing with UTF-8 by making all my offsets in bytes BTW - so I very rarely need to grab a character in a string index as a code point number, and I have a special method for when I need to.

yes, its ope source - I once emailed a copy round the obj-c mailing lost when I first wrote it in fact, though that was back in 1999 or so! You can grab it by git here if you like...

git://toybox4.twisted.org.uk/pfkit

Though I actually keep it under svn. But my young colleagues (< 25) get confused by things which aren't git it seems ;-) Not sure you are going to be very impressed by it - it was originally hacked together to enable me to write and deploy on Windows NT4 when I had absolutely nothing but gcc and the ability to build and run .EXE files as CGI scripts. Which is why I still use static linking for everything. But it does the job, and theres 300,000 lines of code written on top of it which has kept us in business for 20 years, so hey ;)

**Comment by davidchisnall** [comment]
> One question when you say '8 or fewer' for the tiny string, does that include the terminating zero ? i.e. can I just use the address of the pointer as if it was the address of the C-string. That would help a lot!

No, in the tiny string representation we use 7 bits per character and we don't store a 0.  This lets us encode 8 characters plus length in the 61 bits that we have available in the pointer.

> What are the chances of me getting a flag to clang to tell it to make all strings UTF-8 instead of Utf-16 I wonder ? :-) [actually, may look at doing that!]

If you feel like adding it, the place you'd need to change is here:

https://github.com/llvm/llvm-project/blob/acb628b2afb4b43dd0224c393f1ff47abd3b9045/clang/lib/CodeGen/CGObjCGNU.cpp#L1020

Add a flag like 'fgnustep-objc-utf8-strings' and then in that block use the UTF-8 to UTF-16 conversion to get the number of characters (the new ABI stores the number of bytes and the number of characters separately.  These are the same for ASCII and UTF-16, but for UTF-16 knowing both is useful - you can use one for `memcpy` and one for `-length`), but use the original string instead of the UTF-16 version for the data.

> I once emailed a copy round the obj-c mailing lost when I first wrote it in fact, though that was back in 1999 or so!

That's a few years before I learned Objective-C!

Any plans to move to ARC?

**Comment by cyclaero** [comment]
> I forgot to say, the compiler will set `__OBJC_GNUSTEP_RUNTIME_ABI__ >= 20` ...

Which compiler does this under which circumstances? Using the below code, I get the following results:

FreeBSD 12.0-RELEASE-p3 (x86-64)
clang 7.0.1 (port version) - `__OBJC_GNUSTEP_RUNTIME_ABI__ = 16`
clang 6.0.1 (base version) -  `__OBJC_GNUSTEP_RUNTIME_ABI__ = undefined`

FreeBSD 13.0-CURRENT (ARMv7 - BBB, snapshot from 2019-02-14):
clang 7.0.1 (base version) - `__OBJC_GNUSTEP_RUNTIME_ABI__ = 16`

The Test code:

    #import <stdio.h>
    #import <objc/Object.h>
    
    id hello = @"Hello";
    
    __attribute__((objc_root_class))
    @interface A
    {
       Class isa;
       int   cnt;
    }
    @end
    
    @implementation A
    @end
    
    #define ENQUOTING(cvar) #cvar
    #define STRINGIFY(cvar) ENQUOTING(cvar)
    
    int main(int argc, const char *argv[])
    {
       printf("ObjC-ABI %s\n", STRINGIFY(__OBJC_GNUSTEP_RUNTIME_ABI__));
       return 0;
    }

**Comment by minusbat** [comment]
>If you feel like adding it, the place you'd need to change is here:
>
>https://github.com/llvm/llvmproject/blob/acb628b2afb4b43dd0224c393f1ff47abd3b9045/clang/lib/CodeGen/CGObjCGNU.cpp#L1020

Ah, thanks for the pinter! Mmm, looks like I need to upgrade my C++ knowledge, but thats very very useful. I may well do that, or at least give it a try. If I am going to do that I suspect it wouldn't be too hard to make it also never output the small object version of the strings, and then I am back to the state of only having a single representation of a string (which is the real issue thinking about it). OK, when I get some spare time I will go for it.

>That's a few years before I learned Objective-C!

Heh, really? Wow! Actually, I remember you arriving into the GNUstep world very well - like a breath of fresh air into a project that was becoming a bit stuck in it's ways. Have to say, all the work you have put in to Objective-C over the years is *very* appreciated!

>Any plans to move to ARC?

Mmmm, I had a bit of a fiddle about with it, but I think going through all the code and finding any laces where it might break would be very time consuming and I couldn't guarantee finding them all. I would love to be able to do it, but not sure I will ever get around to it. Training people in the use of retain/release is not *that* big a deal, and nobody other than me writes significant amounts of Obj-C at our place anymore. Which is awkward as I have ended up as the only developer of our most critical system.

One thing I would like to do inside the runtime though is to see if I can do something to make it start up faster. We discovered that there is a significant overhead at startup depending on the number of classes included in the binary, even if they are not used. I suspect that the runtime bulls a cache of all methods in all classes before 'main' gets called maybe ? Was thinking of lazy evaluating that if possible, as we have lot of unused classes in the binary (sort of - its one binary with many executions paths, each of which only uses a few classes, but they are all compiled into the binary, so every time it runs they all get added to the runtime. Its a CGI script though, so its started from scratch for every request, and the overhead seems significant).

**Comment by davidchisnall** [comment]
Pre-7 versions of the compiler don't define this macro.  In >=7, it will be set to the minimum of the highest ABI target supported by clang and the version requested in the `-fobjc-runtime=` flag.  For example, if you say `-fobjc-runtime=gnustep-2.1` then clang will still currently set it to 20 because it doesn't know about anything after 2.0.

Clang's ARC migration tool is pretty good.  I've found that it's fairly conservative - it either does the right thing, or it gives you a warning that it can't reason about your code.  In the stuff I ran it on, many of those cases were actually retain/release bugs.

The runtime doesn't build a cache of the methods, but it does have to walk all of the method lists to see if there's a `+load` method.  I might add a flag to say that there isn't one so that the runtime can skip it.  Unfortunately, I didn't think to add a flags field to the category structure, so the runtime will still have to scan all of the methods in a category.  It also has to register all of the selectors.

A lot of this overhead goes down in the 2.0 ABI.  For example, the linker is now able to unique selectors so you have to register one instance of each selector per library in which it's used, not one per compilation unit in which it's used (this was particualrly bad in pre-ARC code, where every compilation unit uses `-retain`, `-release` and `-autorelease`).  This also improves cache usage and gives smaller binaries...

For your particular use case, you might have better luck adding a fastcgi wrapper.  I've done this for an ObjC WebApp project a few years ago and it dramatically improved performance.  Even if the program re-`exec`s itself every 100 requests to kill any memory leaks, you'll probably see the startup time overhead disappear into the noise.

**Comment by minusbat** [comment]
In case you wondered why I went silent, I've spent three months refactoring my code to properly layout the string classes so that the constant one is independent of the others, and am now ready to start on this. Along the way though I've been wondering if, instead of altering clang, I should simply make the code produce a utf-8 representation of the string the first time it is accessed and return that. it would be slower I realise, but a lot more portable as I would not need to have a modified version of the compiler for it to work. Could also make the modifications anyway, as ultimately its just changing what the compiler produces for the constant strings to one of th accepted representation anyway. Thats probably the best approach in fact.

Will let you know how I get on....
